;; Access Control System concepts
(new-type-role {identity} {person} {thing})
(new-type-role {access credentials} {person} {thing})
(new-type {actuator} {device})
(new-type {camera} {device})
(new-type {microphone} {device})
(new-type {recognizer} {thing})
(new-type {snapshot} {thing})
(new-type {finder} {thing})
(new-type {scene} {thing})
(new-type {sensor} {thing})
(new-type {motion} {thing})
(new-type {bolt} {thing})
(new-type {door} {thing})

(new-type {database} {file})
(new-type-role {image format} {image file} {thing})
(new-indv {jpg} {image format})
(new-indv {png} {image format})

(new-type-role {audio format} {audio file} {thing})
(new-indv {wav} {audio format})
(new-indv {mp3} {audio format})
(new-type {sound} {thing})
(new-type {command} {information object})
