#!/bin/sh

pip3 install opencv-python
bash /usr/lib/person-recognizer/models/get-models.sh


#git clone https://github.com/torch/distro.git ~/torch --recursive
#cd ~/torch; bash install-deps;
#./install.sh

