Vagrant.configure("2") do |config|
  config.vm.define "cerberus-pike" do |master|
    master.vm.box = "debian/stretch64"
    master.vm.hostname = 'cerberus-pike'
    master.vm.box_url = "debian/stretch64"
    master.vm.boot_timeout = 300

    master.vm.network :private_network, ip: "192.168.1.100"

    master.vm.provider :virtualbox do |vb|
      vb.customize ["modifyvm", :id, "--natdnshostresolver1", "on"]
      vb.customize ["modifyvm", :id, "--natdnsproxy1", "on"]
      vb.customize ["modifyvm", :id, "--memory", 2048]
      vb.customize ["modifyvm", :id, "--name", "cerberus-pike"]
    end

    master.vm.synced_folder "saltstack/", "/srv/salt/", owner:"vagrant", group:"vagrant"

    master.vm.provision :salt do |salt|
      salt.colorize = true
      salt.install_master = true
      salt.no_minion = false
      salt.minion_id = "cerberus-pike"
      salt.install_type = "stable"
      salt.bootstrap_options = "-A 192.168.1.100"
    end
  end
end
